version: "3.9"

networks:
  copilot-subnet:

services:
  # node.js backend
  copilot-backend-1:
    container_name: copilot-backend-1
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-1/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-2:
    container_name: copilot-backend-2
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-2/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-3:
    container_name: copilot-backend-3
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-3/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-4:
    container_name: copilot-backend-4
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-4/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-5:
    container_name: copilot-backend-5
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-5/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-6:
    container_name: copilot-backend-6
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-6/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-7:
    container_name: copilot-backend-7
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-7/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-8:
    container_name: copilot-backend-8
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-8/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-9:
    container_name: copilot-backend-9
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-9/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-10:
    container_name: copilot-backend-10
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-10/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-11:
    container_name: copilot-backend-11
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-11/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-12:
    container_name: copilot-backend-12
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-12/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-13:
    container_name: copilot-backend-13
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-13/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-14:
    container_name: copilot-backend-14
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-14/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-15:
    container_name: copilot-backend-15
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-15/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-16:
    container_name: copilot-backend-16
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-16/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-17:
    container_name: copilot-backend-17
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-17/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-18:
    container_name: copilot-backend-18
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-18/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-19:
    container_name: copilot-backend-19
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-9/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-20:
    container_name: copilot-backend-20
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-20/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  # nginx frontend
  copilot-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: copilot-frontend
    depends_on:
      copilot-backend-1:
        condition: service_healthy
      copilot-backend-2:
        condition: service_healthy
      copilot-backend-3:
        condition: service_healthy
      copilot-backend-4:
        condition: service_healthy
      copilot-backend-5:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    ports:
      - 0.0.0.0:80:80
    restart: unless-stopped
    healthcheck:
      test: netstat -an | grep 80 > /dev/null || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
