version: "3.9"

networks:
  copilot-subnet:

services:
  # node.js backend
  copilot-backend-1:
    container_name: copilot-backend-1
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-1/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-2:
    container_name: copilot-backend-2
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-2/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-3:
    container_name: copilot-backend-3
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-3/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-4:
    container_name: copilot-backend-4
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-4/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  copilot-backend-5:
    container_name: copilot-backend-5
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.024G
    networks:
      - copilot-subnet
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-backend-5/healthcheck || exit -1
      interval: 5s
      timeout: 10s
      retries: 3

  # nginx frontend
  copilot-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: copilot-frontend
    depends_on:
      copilot-backend-1:
        condition: service_healthy
      copilot-backend-2:
        condition: service_healthy
      copilot-backend-3:
        condition: service_healthy
      copilot-backend-4:
        condition: service_healthy
      copilot-backend-5:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.016G
    networks:
      - copilot-subnet
    ports:
      - 0.0.0.0:80:80
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://copilot-frontend || exit -1
      interval: 5s
      timeout: 10s
      retries: 3
